Optimisation
Lurius-Kitsune/OBJ3D-CPP-DLL-Prog1Lib pull request #16
Opened 2024-11-24 22:40 UTC by Lurius-Kitsune

2024-11-30 18:35 UTC, StazixLS-DEV requested changes
dans user interact y'a plus besoin du array size pour random in collection et t'a mis 2RR au random int

2024-12-07 15:46 UTC, Lurius-Kitsune commented
- fix #18

2024-12-08 01:54 UTC, StazixLS-DEV approved these changes, later dismissed

2024-12-08 13:11 UTC, KAHDOS commented
ok

2024-12-08 13:11 UTC, KAHDOS reviewed
ok

2024-12-08 13:11 UTC, KAHDOS approved these changes
j'ai fail deux fois, c'est chaud

2024-12-08 13:12 UTC, merged